### ISSUE TITLE
Update Delay

### ISSUE THREAD

**Issue by marrold** [evert-arias/LedSync#3]
Hi, thanks for this great libary.

Perhaps I'm reading it wrong, but does the delay in LedSync.update(); not cause the main loop to hang for 20 seconds? 

Thanks again

**Comment by luisgcu** [comment]
@marrold   yep you right this is the idea of the library.

**Comment by evert-arias** [comment]
**LedSync** uses `millis()` to calculate the time between the blinks, that's why it does not cause the main process to hang.
